### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by darkmihai** [Xunil1337/Warcry-CMS#1]
i have some errors

( ! ) Parse error: syntax error, unexpected 'BaseURL' (T_STRING) in C:\wamp\www\configuration\basic.php on line 11
Call Stack
#	Time	Memory	Function	Location
1	0.0004	250800	{main}( )	..\index.php:0
2	0.0006	270872	include_once( 'C:\wamp\www\engine\initialize.php' )	..\index.php:3
3	0.0019	417288	require_once( 'C:\wamp\www\core.php' )	..\initialize.php:5
4	0.0032	423136	require_once( 'C:\wamp\www\configuration\config.php' )	..\core.php:15

<?php
if (!defined('init_config'))
{	
	header('HTTP/1.0 404 not found');
	exit;
}

$config['SiteName'] = 'sitenamehere';

$config['RootPath'] = 'C:\wamp\www\'; 		//(No slash at the end)
$config['BaseURL'] = 'http://127.0.0.1'; 	//(No slash at the end)

//Must be unique for each website
$config['AuthCookieName'] = 'warcry';

//Minifier Settings
//StyleFolderURL rewrites the URLs for the image in the CSS files
$config['StyleFolderURL'] = 'http://127.0.0.1/template/style/'; //(With slash at the end)

//E-mail Address
$config['Email'] = 'info@localhost';

//Time settings
$config['TimeZone'] = 'Europe/Berlin';
$config['TimeZoneOffset'] = '+1';

//Warcry WoW Database URL
$config['WoWDB_URL'] = 'http://127.0.0.1';	//(No slash at the end)
//Complete URL to the power.js
$config['WoWDB_JS'] = 'http://127.0.0.1l/power.js';

**Comment by Xunil1337** [comment]
$config['RootPath'] = 'C:\wamp\www\'; //

(No slash at the end)

**Comment by darkmihai** [comment]
( ! ) Fatal error: Class 'Notifications' not found in C:\wamp\www\engine\initialize.php on line 65
Call Stack
#	Time	Memory	Function	Location
1	0.0151	250432	{main}( )	..\index.php:0
2	0.0211	270528	include_once( 'C:\wamp\www\engine\initialize.php' )	..\index.php:3

**Comment by Xunil1337** [comment]
Later it will be fixxed ...
