### ISSUE TITLE
Login Execute Error

### ISSUE THREAD

**Issue by lolgc1** [Xunil1337/Warcry-CMS#11]
When i create my account does it log me in to AdminCP when i click register

And i also tried to login with the account i created, but it says this:
Fatal error: Call to undefined method CORE::ValidateURLBeforeLogin() in C:\xampp\htdocs\execute_files\login_execute.php on line 25

**Comment by Xunil1337** [comment]
i do not support windows server i use lunux servers and this misteak i know but idk who is the error ...

**Comment by lolgc1** [comment]
I moved it to Linux Web hosting but It makes the same error...

**Comment by DankoDJ** [comment]
Check out the line in the file. Seems you missed .htaccess or the configs...
