### ISSUE TITLE
another error

### ISSUE THREAD

**Issue by darkmihai** [Xunil1337/Warcry-CMS#3]
( ! ) Fatal error: Class 'Notifications' not found in C:\wamp\www\engine\initialize.php on line 63
Call Stack

Time Memory Function Location

1 0.0004 251544 {main}( ) ..\index.php:0
2 0.0007 271640 include_once( 'C:\wamp\www\engine\initialize.php' ) ..\index.php:3

$NOTIFICATIONS = new Notifications();

**Comment by Xunil1337** [comment]
Check it pls if it is fixxed ...

**Comment by darkmihai** [comment]
is not fixed ...

( ! ) Fatal error: Class 'Notifications' not found in C:\wamp\www\engine\initialize.php on line 65
Call Stack
#	Time	Memory	Function	Location
1	0.0004	252176	{main}( )	..\index.php:0
2	0.0006	272240	include_once( 'C:\wamp\www\engine\initialize.php' )	..\index.php:3

**Comment by Xunil1337** [comment]
Okay test it again... if not work, i test it self later ...

**Comment by darkmihai** [comment]
( ! ) Warning: require_once(C:\wamp\www\core.php): failed to open stream: No such file or directory in C:\wamp\www\engine\initialize.php on line 5
Call Stack
#	Time	Memory	Function	Location
1	0.0005	252176	{main}( )	..\index.php:0
2	0.0008	272240	include_once( 'C:\wamp\www\engine\initialize.php' )	..\index.php:3

( ! ) Fatal error: require_once(): Failed opening required 'core.php' (include_path='.;C:\php\pear') in C:\wamp\www\engine\initialize.php on line 5
Call Stack
#	Time	Memory	Function	Location
1	0.0005	252176	{main}( )	..\index.php:0
2	0.0008	272240	include_once( 'C:\wamp\www\engine\initialize.php' )	..\index.php:3

**Comment by darkmihai** [comment]
( ! ) Notice: Undefined variable: TPL in C:\wamp\www\template\pages\home.php on line 9
Call Stack
#	Time	Memory	Function	Location
1	0.0004	252176	{main}( )	..\index.php:0
2	0.0208	1238744	include_once( 'C:\wamp\www\template\pages\home.php' )	..\index.php:99

( ! ) Fatal error: Call to a member function SetParameters() on a non-object in C:\wamp\www\template\pages\home.php on line 9
Call Stack
#	Time	Memory	Function	Location
1	0.0004	252176	{main}( )	..\index.php:0
2	0.0208	1238744	include_once( 'C:\wamp\www\template\pages\home.php' )	..\index.php:99

**Comment by Xunil1337** [comment]
Okay new many Changes, test it !
