### ISSUE TITLE
new errors

### ISSUE THREAD

**Issue by darkmihai** [Xunil1337/Warcry-CMS#4]
Warning: include_once(var/www/html/warcrycms/engine/classes/cache.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 17

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/classes/cache.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 17

Warning: include_once(var/www/html/warcrycms/engine/classes/template.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 18

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/classes/template.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 18

Warning: include_once(var/www/html/warcrycms/engine/classes/multipleError_handler.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 19

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/classes/multipleError_handler.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 19

Warning: include_once(var/www/html/warcrycms/engine/classes/sessions.secure.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 20

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/classes/sessions.secure.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 20

Warning: include_once(var/www/html/warcrycms/engine/classes/accounts.curuser.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 21

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/classes/accounts.curuser.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 21

Warning: include_once(var/www/html/warcrycms/engine/classes/security.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 22

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/classes/security.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 22

Warning: include_once(var/www/html/warcrycms/engine/classes/chmod.calc.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 23

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/classes/chmod.calc.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 23

Warning: include_once(var/www/html/warcrycms/engine/shutdown.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 24

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/shutdown.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 24

Warning: include_once(var/www/html/warcrycms/engine/classes/notifications.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 25

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/classes/notifications.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 25

Warning: include_once(var/www/html/warcrycms/engine/storages/boosts.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 28

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/storages/boosts.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 28

Warning: include_once(var/www/html/warcrycms/engine/storages/rank_strings.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 29

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/storages/rank_strings.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 29

Warning: include_once(var/www/html/warcrycms/engine/storages/avatars.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 30

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/storages/avatars.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 30

Warning: include_once(var/www/html/warcrycms/engine/storages/countries.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 31

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/storages/countries.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 31

Warning: include_once(var/www/html/warcrycms/engine/storages/secret_questions.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 32

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/storages/secret_questions.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 32

Warning: include_once(var/www/html/warcrycms/engine/storages/voteSites.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 33

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/storages/voteSites.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 33

Warning: include_once(var/www/html/warcrycms/engine/storages/pStore_levels.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 34

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/storages/pStore_levels.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 34

Warning: include_once(var/www/html/warcrycms/engine/storages/tp.mapsInfo.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 35

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/storages/tp.mapsInfo.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 35

Warning: include_once(var/www/html/warcrycms/engine/storages/tp.points.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 36

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/storages/tp.points.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 36

Warning: include_once(var/www/html/warcrycms/engine/storages/bt.categories.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 37

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/storages/bt.categories.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 37

Warning: include_once(var/www/html/warcrycms/engine/classes/sessions.none.php): failed to open stream: No such file or directory in /var/www/html/warcrycms/engine/core.php on line 48

Warning: include_once(): Failed opening 'var/www/html/warcrycms/engine/classes/sessions.none.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/warcrycms/engine/core.php on line 48

Fatal error: Class 'multipleErrors' not found in /var/www/html/warcrycms/engine/initialize.php on line 12

**Comment by Xunil1337** [comment]
You post anytime errors, but fixx nothing ... 

My Reallife get on first place, then fun.

Closed
