### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by SymbolixDEV** [Xunil1337/Warcry-CMS#5]
http://curseofdoom.no-ip.org/index.php?page=realm-details

Warning: PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'worldblizz.characters' doesn't exist in C:\xampp\htdocs\engine\server_modules\trinity\realm.stats.php on line 151

Warning: PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'worldblizz.characters' doesn't exist in C:\xampp\htdocs\engine\server_modules\trinity\realm.stats.php on line 157

Any help? 
Add me on skype: found3rr

**Comment by Xunil1337** [comment]
That you can fix with a stupid way...

<?php
if (!defined('init_config'))
{	
	header('HTTP/1.0 404 not found');
	exit;
}
//Website Database Connection Info
$server_config['CORE'] = 'trinity';
//Realms configuration
$realms_config[1] = array(
	'name' 			=> 'TWISTING NETHER', 
	'descr' 		=> 'Blizzlike', 	
	'Database' 		=> array(
		'host' 		=> 'localhost', 
		'name' 		=> 'wrath', <- World DB		
		'user' 		=> 'root', 
		'pass' 		=> '', 
		'encoding' 	=> 'utf8'
	), 
	'address' 		=> '127.0.0.1',
	'port' 			=> '8085',
	'soap_protocol' => 'http',
	'soap_address'  => '127.0.0.1',
	'soap_port'     => '7878',
	'soap_user'     => '',
	'soap_pass'     => '',
	'UPDATE_TIME' 	=> '10 minutes',
);

Add one more options in the config file ... 

'name' 		=> 'wrath', <- World DB	// Here add the Second parameter as characters .,..

it is stupid, 2 variables with name and name but it works...
