### ISSUE TITLE
Php Error I Think

### ISSUE THREAD

**Issue by Shaytanz** [Xunil1337/Warcry-CMS#6]
Strict standards: Only variables should be passed by reference in C:\wamp\www\template\pages\cactivity.php on line 31

Line 31 $res->bindParam(':acc', $CURUSER->get('id'), PDO::PARAM_INT);
I have this error all the time !

**Comment by Xunil1337** [comment]
https://github.com/Xunil1337/Warcry-CMS/issues/7
