### ISSUE TITLE
Php error Whti my Warcry-Cms

### ISSUE THREAD

**Issue by Shaytanz** [Xunil1337/Warcry-CMS#7]
Strict standards: Only variables should be passed by reference in C:\wamp\www\template\pages\cactivity.php on line 31

Line 31 $res->bindParam(':acc', $CURUSER->get('id'), PDO::PARAM_INT);
I have this error all the time !

**Comment by Xunil1337** [comment]
<li><a href="<?php echo $config['BaseURL']; ?>/index.php?page=teleporter">Teleporter</a></li>

You missed some sql querys for your account database, i will see if i can fix it !
