### ISSUE TITLE
Store

### ISSUE THREAD

**Issue by viniroveran** [Xunil1337/Warcry-CMS#8]
Store returns no item name and therefore, you cant select that item to buy

**Comment by Xunil1337** [comment]
Store is not fixxed jet, it is more as simple php, it is more with js ... :(

**Comment by viniroveran** [comment]
I got it fixed and yes, it is a JS problem
Em 05/06/2015 12:11, "Xunil" <notifications@github.com> escreveu:

**Comment by Xunil1337** [comment]
you can send me that fix for public charity ?
