### ISSUE TITLE
Store Items are not Present

### ISSUE THREAD

**Issue by Xunil1337** [Xunil1337/Warcry-CMS#9]
https://github.com/Xunil1337/Warcry-CMS/blob/master/template/js/store.js

This will fixxed soon as possible !

**Comment by DankoDJ** [comment]
Seems the connection to wowhead is not ready.

**Comment by ciya10000** [comment]
Closed ? 
What is this history of close exits in even treat .... Monitoring is really crap here!

**Comment by DankoDJ** [comment]
Seems Xunil is closing issues without fixing them... genius...
